In [5]:
import kagglehub
emirhanai_social_media_usage_and_emotional_well_being_path = kagglehub.dataset_download('emirhanai/social-media-usage-and-emotional-well-being')

print('Data source import complete.')

Using Colab cache for faster access to the 'social-media-usage-and-emotional-well-being' dataset.
Data source import complete.

<h1><b><p style="background-image: url(https://i.postimg.cc/0Qwf8YX6/2927262.jpg);font-family:camtasia;font-size:110%;color:white;text-align:center;border-radius:15px 50px; padding:7px; border:solid 2px #09375b; box-shadow: 10px 10px 10px #042b4c">Project Title: Social Media insights through Big Data Analytics</p></b></h1>

# About Dataset
Files:

    train.csv: Data for training models.
    test.csv: Data for testing models.
    val.csv: Data for validation purposes.

__Dataset Overview:__

  🌐 Source: __Dataset is taken from [Kaggle](https://www.kaggle.com/datasets/emirhanai/social-media-usage-and-emotional-well-being/data)__

# Importing Libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [7]:
# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Data Loading

In [8]:
from google.colab import files
uploaded = files.upload()  # Select 'data.zip'

Saving socialmedia_data.zip to socialmedia_data.zip

In [9]:
import zipfile
import os

with zipfile.ZipFile("socialmedia_data.zip", "r") as zip_ref:
    zip_ref.extractall("/content/")  # Extract files here

print("Extracted files:", os.listdir("/content/"))

Extracted files: ['.config', 'socialmedia_data.zip', 'test.csv', 'train.csv', 'val.csv', 'sample_data']

In [10]:
train_df = pd.read_csv("/content/train.csv", on_bad_lines="skip")
test_df = pd.read_csv("/content/test.csv", on_bad_lines="skip")
val_df = pd.read_csv("/content/val.csv", on_bad_lines="skip")

print("✅ All files loaded!")

✅ All files loaded!

In [11]:
# viwing the traing data, test data and validation data
print("Training Data:")
display(train_df.head())
print("----------------------------------------------------------------------")
print("Testing Data:")
display(test_df.head())
print("----------------------------------------------------------------------")
print("Validation Data:")
display(val_df.head())

Training Data:

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,25,Female,Instagram,120.0,3.0,45.0,10.0,12.0,Happiness
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,30,Male,Twitter,90.0,5.0,20.0,25.0,30.0,Anger
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------------------------------------
Testing Data:

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,500.0,27,Female,Snapchat,120.0,4.0,40.0,18.0,22.0,Neutral
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,488.0,21,Non-binary,Snapchat,60.0,1.0,18.0,7.0,12.0,Neutral
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------------------------------------
Validation Data:

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.0,31,Male,Instagram,170,5.0,80.0,20.0,35,Happiness,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,877.0,32,Female,Instagram,155,6.0,75.0,25.0,38,Happiness,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# training data info
print("Traing Data Info:")
train_df.info()

Traing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004 entries, 0 to 2003
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     1001 non-null   object
 1   Age                         1001 non-null   object
 2   Gender                      1000 non-null   object
 3   Platform                    1000 non-null   object
 4   Daily_Usage_Time (minutes)  1000 non-null   float64
 5   Posts_Per_Day               1000 non-null   float64
 6   Likes_Received_Per_Day      1000 non-null   float64
 7   Comments_Received_Per_Day   1000 non-null   float64
 8   Messages_Sent_Per_Day       1000 non-null   float64
 9   Dominant_Emotion            1000 non-null   object
dtypes: float64(5), object(5)
memory usage: 156.7+ KB

In [13]:
# testing data info
print("Testing Data Info:")
test_df.info()

Testing Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     103 non-null    float64
 1   Age                         103 non-null    object
 2   Gender                      103 non-null    object
 3   Platform                    103 non-null    object
 4   Daily_Usage_Time (minutes)  103 non-null    float64
 5   Posts_Per_Day               103 non-null    float64
 6   Likes_Received_Per_Day      103 non-null    float64
 7   Comments_Received_Per_Day   103 non-null    float64
 8   Messages_Sent_Per_Day       103 non-null    float64
 9   Dominant_Emotion            103 non-null    object
dtypes: float64(6), object(4)
memory usage: 16.2+ KB

In [14]:
# validation data info
print("Validation Data Info:")
val_df.info()

Validation Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     148 non-null    float64
 1   Age                         148 non-null    object
 2   Gender                      148 non-null    object
 3   Platform                    148 non-null    object
 4   Daily_Usage_Time (minutes)  148 non-null    object
 5   Posts_Per_Day               148 non-null    float64
 6   Likes_Received_Per_Day      148 non-null    float64
 7   Comments_Received_Per_Day   148 non-null    float64
 8   Messages_Sent_Per_Day       148 non-null    object
 9   Dominant_Emotion            145 non-null    object
 10  Unnamed: 10                 3 non-null      object
dtypes: float64(4), object(7)
memory usage: 25.6+ KB

* Shape of the training, testing, and validation data.

In [15]:
print(f"There are {train_df.shape[0]} rows and {train_df.shape[1]} columns in the training data.")
print(f"There are {test_df.shape[0]} rows and {test_df.shape[1]} columns in the testing data.")
print(f"There are {val_df.shape[0]} rows and {val_df.shape[1]} columns in the validation data.")

There are 2004 rows and 10 columns in the training data.
There are 206 rows and 10 columns in the testing data.
There are 296 rows and 11 columns in the validation data.

In [16]:
# checking for null values
print("Training Data:")
display(train_df.isnull().sum())
print("----------------------------------------------------------------------")
print("Testing Data:")
display(test_df.isnull().sum())
print("----------------------------------------------------------------------")
print("Validation Data:")
display(val_df.isnull().sum())

Training Data:

User_ID                       1003
Age                           1003
Gender                        1004
Platform                      1004
Daily_Usage_Time (minutes)    1004
Posts_Per_Day                 1004
Likes_Received_Per_Day        1004
Comments_Received_Per_Day     1004
Messages_Sent_Per_Day         1004
Dominant_Emotion              1004
dtype: int64

----------------------------------------------------------------------
Testing Data:

User_ID                       103
Age                           103
Gender                        103
Platform                      103
Daily_Usage_Time (minutes)    103
Posts_Per_Day                 103
Likes_Received_Per_Day        103
Comments_Received_Per_Day     103
Messages_Sent_Per_Day         103
Dominant_Emotion              103
dtype: int64

----------------------------------------------------------------------
Validation Data:

User_ID                       148
Age                           148
Gender                        148
Platform                      148
Daily_Usage_Time (minutes)    148
Posts_Per_Day                 148
Likes_Received_Per_Day        148
Comments_Received_Per_Day     148
Messages_Sent_Per_Day         148
Dominant_Emotion              151
Unnamed: 10                   293
dtype: int64

# Exploratory Data Analysis (EDA)

In [17]:
train_df.head()

,User_ID,Age,Gender,Platform,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day,Dominant_Emotion
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,25,Female,Instagram,120.0,3.0,45.0,10.0,12.0,Happiness
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,30,Male,Twitter,90.0,5.0,20.0,25.0,30.0,Anger
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* Coloum in our data:

In [18]:
# list of coloums in the training data
train_df.columns

Index(['User_ID', 'Age', 'Gender', 'Platform', 'Daily_Usage_Time (minutes)',
       'Posts_Per_Day', 'Likes_Received_Per_Day', 'Comments_Received_Per_Day',
       'Messages_Sent_Per_Day', 'Dominant_Emotion'],
      dtype='object')

### Describe the training data

In [19]:
train_df.describe()

,Daily_Usage_Time (minutes),Posts_Per_Day,Likes_Received_Per_Day,Comments_Received_Per_Day,Messages_Sent_Per_Day
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,95.950000,3.321000,39.898000,15.611000,22.560000
std,38.850442,1.914582,26.393867,8.819493,8.516274
min,40.000000,1.000000,5.000000,2.000000,8.000000
25%,65.000000,2.000000,20.000000,8.000000,17.750000
50%,85.000000,3.000000,33.000000,14.000000,22.000000
75%,120.000000,4.000000,55.000000,22.000000,28.000000
max,200.000000,8.000000,110.000000,40.000000,50.000000

### Age Distribution

In [20]:
train_df['Age'].isnull().sum()

np.int64(1003)

In [21]:
train_df['Age'].unique()

array([nan, '25', '30', '22', '28', '33', '21', '27', '24', '29', '31',
       '23', '26', '34', '35', '32', 'Male', 'Female', 'Non-binary',
       ' işte mevcut veri kümesini 1000 satıra tamamlıyorum:'],
      dtype=object)

In [22]:
# removing the Male, Female, Non-binary, and işte mevcut veri kümesini 1000 satıra tamamlıyorum:

# Replace non-numeric values with NaN
train_df['Age'] = pd.to_numeric(train_df['Age'], errors='coerce')

# Handle NaN values
train_df['Age'].fillna(train_df['Age'].median(), inplace=True)

In [23]:
train_df['Age'].unique()

array([27., 25., 30., 22., 28., 33., 21., 24., 29., 31., 23., 26., 34.,
       35., 32.])

In [24]:
plt = px.histogram(train_df, x='Age', title='Age Distribution')
plt.show()

### Gender Distribution

In [25]:
train_df['Gender'].unique()

array([nan, 'Female', 'Male', 'Non-binary', '27', '24', '29', '33', '31',
       '22', '25', '28', '30', '23', '34', '26', '35', '21', '32'],
      dtype=object)

In [26]:
# Function to replace numeric values with NaN
def clean_gender_column(gender_value):
    try:
        # Try converting the value to float, if it succeeds it's a numeric value
        float(gender_value)
        return np.nan
    except ValueError:
        # If conversion fails, it's a valid gender entry
        return gender_value

# Apply the function to the Gender column
train_df['Gender'] = train_df['Gender'].apply(clean_gender_column)

# Fill NaN values with a placeholder or drop them
# Here we fill NaN values with 'Unknown'
train_df['Gender'].fillna('Unknown', inplace=True)

# Verify the unique values after cleaning
print(train_df['Gender'].unique())

['Unknown' 'Female' 'Male' 'Non-binary']

In [27]:
train_df['Gender'].unique()

array(['Unknown', 'Female', 'Male', 'Non-binary'], dtype=object)

In [28]:
train_df['Gender'].value_counts()

Gender
Unknown       1080
Female         344
Male           332
Non-binary     248
Name: count, dtype: int64

In [29]:
plt = px.histogram(train_df, x='Gender', title='Gender Distribution')
plt.show()

### Platform Distribution

In [30]:
train_df['Platform'].unique()

array([nan, 'Instagram', 'Twitter', 'Facebook', 'LinkedIn', 'Whatsapp',
       'Telegram', 'Snapchat'], dtype=object)

In [31]:
train_df['Platform'].value_counts()

Platform
Instagram    250
Twitter      200
Facebook     190
LinkedIn     120
Whatsapp      80
Telegram      80
Snapchat      80
Name: count, dtype: int64

* Let's Impute the nan with the mode

In [32]:
# filling with mode
train_df['Platform'].fillna(train_df['Platform'].mode()[0], inplace=True)

In [33]:
train_df['Platform'].unique()

array(['Instagram', 'Twitter', 'Facebook', 'LinkedIn', 'Whatsapp',
       'Telegram', 'Snapchat'], dtype=object)

In [34]:
train_df['Platform'].value_counts()

Platform
Instagram    1254
Twitter       200
Facebook      190
LinkedIn      120
Whatsapp       80
Telegram       80
Snapchat       80
Name: count, dtype: int64

In [35]:
plt = px.histogram(train_df, x='Platform', title='Platform Distribution')
plt.show()

### Daily Usage Time (minutes) Distribution

In [36]:
plt = px.histogram(train_df, x='Daily_Usage_Time (minutes)', title='Daily Usage Time Distribution')
plt.show()

### Post Per Day Distribution

In [37]:
train_df['Posts_Per_Day'].unique()

array([nan,  3.,  5.,  2.,  8.,  1.,  4.,  6.,  7.])

In [38]:
# fill with mode
train_df['Posts_Per_Day'].fillna(train_df['Posts_Per_Day'].mode()[0], inplace=True)

In [39]:
plt = px.histogram(train_df, x='Posts_Per_Day', title='Posts Per Day Distribution')
plt.show()

### Likes Per Day Distribution

In [40]:
train_df['Likes_Received_Per_Day'].unique()

array([ nan,  45.,  20.,  15., 100.,   5.,  60.,  30.,  25.,  10.,  80.,
        35.,  12.,  90.,  40.,  55.,  33.,   8.,  70.,  28.,  11.,  95.,
        18.,   9.,  85.,  38.,   6.,  13.,  75.,  27.,  88.,  22.,  78.,
        29.,  50.,  36.,  72.,  65., 110.,  14.,  17., 105.,  43.,  37.,
        42.,  48.,  21.,  24.,  23.,  83.])

In [41]:
# filling wih mode
train_df['Likes_Received_Per_Day'].fillna(train_df['Likes_Received_Per_Day'].mode()[0], inplace=True)

In [42]:
plt = px.histogram(train_df, x='Likes_Received_Per_Day', title='Posts Per Day Distribution')
plt.show()

### Comments Per Day Distribution

In [43]:
train_df['Comments_Received_Per_Day'].unique()

array([nan, 10., 25.,  5., 30.,  2., 15., 12.,  3., 20.,  7.,  4., 23.,
       18., 22., 14., 26.,  8., 19., 17., 11.,  6.,  9., 13., 40., 16.,
       35., 38., 28., 36., 33.])

In [44]:
# filling with mode
train_df['Comments_Received_Per_Day'].fillna(train_df['Comments_Received_Per_Day'].mode()[0], inplace=True)

In [45]:
train_df['Comments_Received_Per_Day'].unique()

array([18., 10., 25.,  5., 30.,  2., 15., 12.,  3., 20.,  7.,  4., 23.,
       22., 14., 26.,  8., 19., 17., 11.,  6.,  9., 13., 40., 16., 35.,
       38., 28., 36., 33.])

In [46]:
plt = px.histogram(train_df, x='Comments_Received_Per_Day', title='Posts Per Day Distribution')
plt.show()

### Messages Per Day Distribution

In [47]:
plt = px.histogram(train_df, x='Messages_Sent_Per_Day', title='Posts Per Day Distribution')
plt.show()

### Emotion Distribution

In [48]:
train_df['Dominant_Emotion'].unique()

array([nan, 'Happiness', 'Anger', 'Neutral', 'Anxiety', 'Boredom',
       'Sadness'], dtype=object)

In [49]:
# fill with mode
train_df['Dominant_Emotion'].fillna(train_df['Dominant_Emotion'].mode()[0], inplace=True)

In [50]:
plt = px.pie(train_df, names='Dominant_Emotion', title='Dominant Emotion Distribution')
# adding the values to the pie section
plt.update_traces(textposition='inside', textinfo='percent+label')
plt.show()

## Relationship Between Variables

### Gender and Platform

In [51]:
# Group the data by gender and platform
grouped = train_df.groupby(['Gender', 'Platform'])

# Count the number of rows in each group
counts = grouped.size()

# Print the counts
print(counts)

Gender      Platform
Female      Facebook       10
            Instagram     150
            LinkedIn       40
            Snapchat       28
            Twitter        66
            Whatsapp       50
Male        Facebook       38
            Instagram      76
            LinkedIn       48
            Telegram       50
            Twitter       102
            Whatsapp       18
Non-binary  Facebook      130
            Instagram      10
            LinkedIn       30
            Snapchat       40
            Telegram       18
            Twitter        20
Unknown     Facebook       12
            Instagram    1018
            LinkedIn        2
            Snapchat       12
            Telegram       12
            Twitter        12
            Whatsapp       12
dtype: int64

In [52]:
plt = px.histogram(train_df, x='Gender', color='Platform', title='Platform by Gender Usage')
plt.show()

### Age and Gender

In [53]:
# grouping age with gender
grouped = train_df.groupby(['Age', 'Gender'])

# count the number of rows in each group
counts = grouped.size()

# print the counts
print(counts)

Age   Gender
21.0  Female          20
      Male            10
      Non-binary      26
22.0  Female          48
      Male             8
      Non-binary      18
23.0  Female          10
      Male             8
      Non-binary      30
24.0  Female          26
      Male            10
      Non-binary      28
25.0  Female          40
      Male            24
26.0  Female           8
      Male            28
      Non-binary      30
27.0  Female          28
      Male            44
      Non-binary      20
      Unknown       1080
28.0  Female          36
      Male            28
      Non-binary      28
29.0  Female          28
      Male            30
      Non-binary      32
30.0  Female           8
      Male            40
31.0  Female           8
      Male            54
32.0  Female          28
      Male            10
33.0  Female          18
      Male            10
      Non-binary      28
34.0  Female          18
      Male            10
      Non-binary       8
35.0  Female          20
      Male            18
dtype: int64

In [54]:
plt = px.histogram(train_df, x='Age', color='Gender', title='Age by Gender')
plt.show()

### Gender and Platform VS Daily Usage Time (minutes)

In [55]:
plt = px.histogram(train_df, x='Posts_Per_Day', y='Platform' ,color='Gender', title='Posts Per Day by Gender')
plt.show()

### Gender VS Emotions

In [56]:
# checking the Gender againest the Dominant_Emotion
grouped = train_df.groupby(['Gender', 'Dominant_Emotion'])

# count the number of rows in each group
counts = grouped.size()

# print the counts
print(counts)

Gender      Dominant_Emotion
Female      Anger                 54
            Anxiety               54
            Boredom               30
            Happiness            102
            Neutral               56
            Sadness               48
Male        Anger                 58
            Anxiety               56
            Boredom               54
            Happiness             66
            Neutral               46
            Sadness               52
Non-binary  Anger                 10
            Anxiety               46
            Boredom               46
            Happiness             18
            Neutral               82
            Sadness               46
Unknown     Anger                  8
            Anxiety               14
            Boredom               10
            Happiness           1018
            Neutral               16
            Sadness               14
dtype: int64

In [57]:
# ploting
plt = px.histogram(train_df, x='Gender', color='Dominant_Emotion', title='Dominant Emotion by Gender')
plt.show()

### Platform VS Emotions

In [58]:
# checking the Platformagainest the Dominant_Emotion
grouped = train_df.groupby(['Platform', 'Dominant_Emotion'])

# count the number of rows in each group
counts = grouped.size()

# print the counts
print(counts)

Platform   Dominant_Emotion
Facebook   Anxiety               50
           Boredom               40
           Neutral               70
           Sadness               30
Instagram  Anger                 10
           Anxiety               30
           Happiness           1174
           Neutral               20
           Sadness               20
LinkedIn   Anxiety               20
           Boredom               70
           Neutral               20
           Sadness               10
Snapchat   Anxiety               20
           Happiness             10
           Neutral               20
           Sadness               30
Telegram   Anger                 10
           Anxiety               10
           Boredom               10
           Neutral               30
           Sadness               20
Twitter    Anger                 80
           Anxiety               20
           Boredom               20
           Happiness             10
           Neutral               20
           Sadness               50
Whatsapp   Anger                 30
           Anxiety               20
           Happiness             10
           Neutral               20
dtype: int64

In [59]:
Plt = px.histogram(train_df, x='Platform', color='Dominant_Emotion', title='Dominant Emotion by Platform')
Plt.show()

In [60]:
# Create a contingency table
contingency_table = pd.crosstab(train_df['Platform'], train_df['Dominant_Emotion'])

# Plot the heatmap
fig = px.imshow(contingency_table, title='Platform vs Dominant Emotion Heatmap')
fig.show()

### Time Spent VS Emotions

In [61]:
# Daily Usage time by Dominant_Emotion
plt = px.histogram(train_df, x='Daily_Usage_Time (minutes)', color='Dominant_Emotion', title='Time Usage by Dominant Emotion')
plt.show()

### Likes Received VS Emotions
* This is the last realation I'll be looking in this data.

In [62]:
plt = px.histogram(train_df, x='Likes_Received_Per_Day', color='Dominant_Emotion', title='Likes Received vs Dominant Emotion')
plt.show()

# Model Training

In [63]:
# Import the necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

In [64]:
# Checking for missing values
train_df.isnull().sum()

User_ID                       1003
Age                              0
Gender                           0
Platform                         0
Daily_Usage_Time (minutes)    1004
Posts_Per_Day                    0
Likes_Received_Per_Day           0
Comments_Received_Per_Day        0
Messages_Sent_Per_Day         1004
Dominant_Emotion                 0
dtype: int64

In [65]:
# Let's drop the missing values
train_df.dropna(inplace=True)

In [66]:
# Define features and target
X = train_df.drop(columns=['Dominant_Emotion', 'User_ID']) # Features
y = train_df['Dominant_Emotion'] # Target

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [67]:
# Define preprocessing steps. Seeperating the numerical and categorical features
numeric_features = ['Daily_Usage_Time (minutes)', 'Posts_Per_Day', 'Likes_Received_Per_Day', 'Comments_Received_Per_Day', 'Messages_Sent_Per_Day']
categorical_features = ['Age', 'Gender', 'Platform']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)])

### XGBoost Classifier

In [68]:
from sklearn.preprocessing import LabelEncoder
# Encode target labels as integers
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [69]:
# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# XGBoost Classifier
xgb_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                               ('classifier', XGBClassifier(random_state=42))])

xgb_pipeline.fit(X_train, y_train)
y_pred_xgb = xgb_pipeline.predict(X_test)

In [71]:
#Decode the predicted labels back to original string labels for the report

y_test_decoded = label_encoder.inverse_transform(y_test)
y_pred_xgb_decoded = label_encoder.inverse_transform(y_pred_xgb)

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test_decoded, y_pred_xgb_decoded)

print("XGBoost Classifier Report:")
print(classification_report(y_test_decoded, y_pred_xgb_decoded))

XGBoost Classifier Report:
              precision    recall  f1-score   support

       Anger       1.00      1.00      1.00        29
     Anxiety       1.00      0.95      0.97        39
     Boredom       0.94      1.00      0.97        31
   Happiness       1.00      1.00      1.00        35
     Neutral       0.98      0.98      0.98        42
     Sadness       1.00      1.00      1.00        24

    accuracy                           0.98       200
   macro avg       0.99      0.99      0.99       200
weighted avg       0.99      0.98      0.99       200